apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
   replicas: 3
   selector:
     matchLabels:
       app: conversaopeso
   template:
     metadata:
       labels:
         app: conversaopeso
     spec:
       containers:
         - name: conversaopeso
           image: luismartorano/conversao-peso:latest
           ports:
             - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: conversaopeso
spec: 
  selector: 
    app: conversaopeso
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: http
      #nodePort: 30001
  type: LoadBalancer
  

